/*
 Navicat Premium Dump SQL

 Source Server         : POSTGRE_SQL_LOCAL
 Source Server Type    : PostgreSQL
 Source Server Version : 170009 (170009)
 Source Host           : localhost:5432
 Source Catalog        : sicaeUsuario
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170009 (170009)
 File Encoding         : 65001

 Date: 26/05/2026 12:37:18
*/


-- ----------------------------
-- Sequence structure for programaEducativo_idPrograma_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."programaEducativo_idPrograma_seq";
CREATE SEQUENCE "public"."programaEducativo_idPrograma_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for rol_idrol_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."rol_idrol_seq";
CREATE SEQUENCE "public"."rol_idrol_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for tipoUsuario_idTipo_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tipoUsuario_idTipo_seq";
CREATE SEQUENCE "public"."tipoUsuario_idTipo_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for usuario_idUsuario_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."usuario_idUsuario_seq";
CREATE SEQUENCE "public"."usuario_idUsuario_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for programaEducativo
-- ----------------------------
DROP TABLE IF EXISTS "public"."programaEducativo";
CREATE TABLE "public"."programaEducativo" (
  "idPrograma" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  "nombre" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "estatus" bit(1) NOT NULL
)
;

-- ----------------------------
-- Records of programaEducativo
-- ----------------------------
INSERT INTO "public"."programaEducativo" VALUES (1, 'Lic. en Ingeniería de Software', '1');
INSERT INTO "public"."programaEducativo" VALUES (2, 'Lic. en Ingeniería de Ciberseguridade Infraestructura de Cómputo', '1');
INSERT INTO "public"."programaEducativo" VALUES (3, 'Lic. en Ingeniería en Sistemas y Tecnologías de la Información', '1');
INSERT INTO "public"."programaEducativo" VALUES (4, 'Lic. en Ingeniería en Ciencia de Datos', '1');
INSERT INTO "public"."programaEducativo" VALUES (5, 'Maestría en Sistemas Interactivos Centrados en el Usuario', '1');
INSERT INTO "public"."programaEducativo" VALUES (6, 'Doctorado en Ciencias de la Computación (DCC)', '1');
INSERT INTO "public"."programaEducativo" VALUES (7, 'Especialización en Métodos Estadísticos', '1');

-- ----------------------------
-- Table structure for rol
-- ----------------------------
DROP TABLE IF EXISTS "public"."rol";
CREATE TABLE "public"."rol" (
  "idrol" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  "nombre" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "estatus" bit(1) NOT NULL
)
;

-- ----------------------------
-- Records of rol
-- ----------------------------
INSERT INTO "public"."rol" VALUES (1, 'administrador', '1');
INSERT INTO "public"."rol" VALUES (2, 'invitado', '1');

-- ----------------------------
-- Table structure for tipoUsuario
-- ----------------------------
DROP TABLE IF EXISTS "public"."tipoUsuario";
CREATE TABLE "public"."tipoUsuario" (
  "idTipo" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  "nombre" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "estatus" bit(1) NOT NULL
)
;

-- ----------------------------
-- Records of tipoUsuario
-- ----------------------------
INSERT INTO "public"."tipoUsuario" VALUES (1, 'Docente', '1');
INSERT INTO "public"."tipoUsuario" VALUES (2, 'Administrativo', '1');
INSERT INTO "public"."tipoUsuario" VALUES (3, 'Alumno', '1');

-- ----------------------------
-- Table structure for usuario
-- ----------------------------
DROP TABLE IF EXISTS "public"."usuario";
CREATE TABLE "public"."usuario" (
  "idUsuario" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "nombre" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "apellidoPaterno" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "apellidoMaterno" varchar(50) COLLATE "pg_catalog"."default",
  "claveUsuario" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "telefono" varchar(10) COLLATE "pg_catalog"."default",
  "username" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "password" text COLLATE "pg_catalog"."default" NOT NULL,
  "estatus" bit(1) NOT NULL,
  "idRol" int2 NOT NULL,
  "idTipoUsuario" int2 NOT NULL,
  "idProgramaEducativo" int2 NOT NULL,
  "tiempoCreacion" timestamp(6),
  "tempoActualizacion" timestamp(6)
)
;

-- ----------------------------
-- Records of usuario
-- ----------------------------
INSERT INTO "public"."usuario" VALUES (1, 'Administrador', 'fei', NULL, 'fei', 'admin@example.com', NULL, 'admin', '$2a$10$oJoW27DxpxVlVjYv3FvNG.oJIqimwEkYiZr5l142bdUkK6XnK4bGO', '1', 1, 1, 3, '2026-05-25 19:30:55', NULL);

-- ----------------------------
-- View structure for usuarioFullInfo
-- ----------------------------
DROP VIEW IF EXISTS "public"."usuarioFullInfo";
CREATE VIEW "public"."usuarioFullInfo" AS  SELECT u."idUsuario",
    u.nombre,
    u."apellidoPaterno",
    u."apellidoMaterno",
    u."claveUsuario",
    u.email,
    u.telefono,
    u.username,
    u.password,
    u.estatus,
    u."idRol",
    r.nombre AS rol,
    u."idTipoUsuario",
    tu.nombre AS "tipoUsuario",
    u."idProgramaEducativo",
    pe.nombre AS "programaEducativo",
    u."tiempoCreacion",
    u."tempoActualizacion"
   FROM usuario u
     JOIN rol r ON r.idrol = u."idRol"
     JOIN "tipoUsuario" tu ON tu."idTipo" = u."idTipoUsuario"
     JOIN "programaEducativo" pe ON pe."idPrograma" = u."idProgramaEducativo";

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."programaEducativo_idPrograma_seq"
OWNED BY "public"."programaEducativo"."idPrograma";
SELECT setval('"public"."programaEducativo_idPrograma_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."rol_idrol_seq"
OWNED BY "public"."rol"."idrol";
SELECT setval('"public"."rol_idrol_seq"', 2, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."tipoUsuario_idTipo_seq"
OWNED BY "public"."tipoUsuario"."idTipo";
SELECT setval('"public"."tipoUsuario_idTipo_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."usuario_idUsuario_seq"
OWNED BY "public"."usuario"."idUsuario";
SELECT setval('"public"."usuario_idUsuario_seq"', 1, true);

-- ----------------------------
-- Auto increment value for programaEducativo
-- ----------------------------
SELECT setval('"public"."programaEducativo_idPrograma_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table programaEducativo
-- ----------------------------
ALTER TABLE "public"."programaEducativo" ADD CONSTRAINT "programaEducativo_pkey" PRIMARY KEY ("idPrograma");

-- ----------------------------
-- Auto increment value for rol
-- ----------------------------
SELECT setval('"public"."rol_idrol_seq"', 2, true);

-- ----------------------------
-- Primary Key structure for table rol
-- ----------------------------
ALTER TABLE "public"."rol" ADD CONSTRAINT "rol_pkey" PRIMARY KEY ("idrol");

-- ----------------------------
-- Auto increment value for tipoUsuario
-- ----------------------------
SELECT setval('"public"."tipoUsuario_idTipo_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table tipoUsuario
-- ----------------------------
ALTER TABLE "public"."tipoUsuario" ADD CONSTRAINT "tipoUsuario_pkey" PRIMARY KEY ("idTipo");

-- ----------------------------
-- Auto increment value for usuario
-- ----------------------------
SELECT setval('"public"."usuario_idUsuario_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table usuario
-- ----------------------------
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_pkey" PRIMARY KEY ("idUsuario");

-- ----------------------------
-- Foreign Keys structure for table usuario
-- ----------------------------
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_idProgramaEducativo_fkey" FOREIGN KEY ("idProgramaEducativo") REFERENCES "public"."programaEducativo" ("idPrograma") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_idRol_fkey" FOREIGN KEY ("idRol") REFERENCES "public"."rol" ("idrol") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_idTipoUsuario_fkey" FOREIGN KEY ("idTipoUsuario") REFERENCES "public"."tipoUsuario" ("idTipo") ON DELETE NO ACTION ON UPDATE NO ACTION;
