DROP VIEW IF EXISTS "usuarioFullInfo";
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS "programaEducativo";
DROP TABLE IF EXISTS rol;
DROP TABLE IF EXISTS "tipoUsuario";

CREATE TABLE "programaEducativo" (
  "idPrograma" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  estatus bit(1) NOT NULL
);

CREATE TABLE rol (
  idrol int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  estatus bit(1) NOT NULL
);

CREATE TABLE "tipoUsuario" (
  "idTipo" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  estatus bit(1) NOT NULL
);

CREATE TABLE usuario (
  "idUsuario" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  "apellidoPaterno" varchar(50) NOT NULL,
  "apellidoMaterno" varchar(50),
  "claveUsuario" varchar(10) NOT NULL,
  email varchar(255) NOT NULL,
  telefono varchar(10),
  username varchar(30) NOT NULL,
  password text NOT NULL,
  estatus bit(1) NOT NULL,
  "idRol" int NOT NULL,
  "idTipoUsuario" int NOT NULL,
  "idProgramaEducativo" int NOT NULL,
  "tiempoCreacion" timestamp,
  "tempoActualizacion" timestamp,
  CONSTRAINT usuario_idrol_fkey FOREIGN KEY ("idRol") REFERENCES rol(idrol),
  CONSTRAINT usuario_idtipousuario_fkey FOREIGN KEY ("idTipoUsuario") REFERENCES "tipoUsuario"("idTipo"),
  CONSTRAINT usuario_idprograma_fkey FOREIGN KEY ("idProgramaEducativo") REFERENCES "programaEducativo"("idPrograma")
);

INSERT INTO "programaEducativo" VALUES
(1, 'Lic. en Ingenieria de Software', B'1'),
(2, 'Lic. en Ingenieria de Ciberseguridad e Infraestructura de Computo', B'1'),
(3, 'Lic. en Ingenieria en Sistemas y Tecnologias de la Informacion', B'1'),
(4, 'Lic. en Ingenieria en Ciencia de Datos', B'1'),
(5, 'Maestria en Sistemas Interactivos Centrados en el Usuario', B'1'),
(6, 'Doctorado en Ciencias de la Computacion', B'1'),
(7, 'Especializacion en Metodos Estadisticos', B'1');

INSERT INTO rol VALUES
(1, 'administrador', B'1'),
(2, 'invitado', B'1');

INSERT INTO "tipoUsuario" VALUES
(1, 'Docente', B'1'),
(2, 'Administrativo', B'1'),
(3, 'Alumno', B'1');

INSERT INTO usuario VALUES
(1, 'Administrador', 'fei', NULL, 'fei', 'admin@example.com', NULL, 'admin',
 '$2a$10$kOs/guKI1ozK1YV3wcfZIe3gbQe3kdHnLazKo1sA4zAdDxHBlEZXS',
 B'1', 1, 1, 3, '2026-05-25 19:30:55', NULL);

CREATE VIEW "usuarioFullInfo" AS
SELECT u."idUsuario",
       u.nombre,
       u."apellidoPaterno",
       u."apellidoMaterno",
       u."claveUsuario",
       u.email,
       u.telefono,
       u.username,
       u.password,
       u.estatus,
       u."idRol",
       r.nombre AS rol,
       u."idTipoUsuario",
       tu.nombre AS "tipoUsuario",
       u."idProgramaEducativo",
       pe.nombre AS "programaEducativo",
       u."tiempoCreacion",
       u."tempoActualizacion"
FROM usuario u
JOIN rol r ON r.idrol = u."idRol"
JOIN "tipoUsuario" tu ON tu."idTipo" = u."idTipoUsuario"
JOIN "programaEducativo" pe ON pe."idPrograma" = u."idProgramaEducativo";

SELECT setval(pg_get_serial_sequence('"programaEducativo"', 'idPrograma'), 7, true);
SELECT setval(pg_get_serial_sequence('rol', 'idrol'), 2, true);
SELECT setval(pg_get_serial_sequence('"tipoUsuario"', 'idTipo'), 3, true);
SELECT setval(pg_get_serial_sequence('usuario', 'idUsuario'), 1, true);
